### ISSUE TITLE
change-submit Trigger not working

### ISSUE THREAD

**Issue by dtnguyen277** [saadbruno/perforce-discord-webhook#2]
Hey, I'm having a similar issue to the issue posted 4 months ago.

When I run the script manually, my discord webhook works and I can see a changelist update.

However when i setup the trigger via
`discord change-submit //depot/... "/bin/bash /home/perforce/perforce_discord_webhook.sh %changelist% <insert webhook here>`
it doesn't work.
I have verified the script directory and webhook.

One thing to note is I can't run 
`P4 Trust` 
when when my P4PORT is set to ssl:localhost:1666 it just complains saying
`Perforce client error:
        Connect to server failed; check $P4PORT.
        connect: 127.0.0.1:1666: Connection refused`
But when i set my P4PORT to my public IP it works fine.

I'm suspecting this has something to do with my Trigger not firing properly.
I was wondering if you had any pointers to how I should fix this.
Thanks!

**Comment by dtnguyen277** [comment]
Boiled down the issue a little more
`Perforce password (P4PASSWD) invalid or unset.`
I'm not too sure how to set this.
I've tried using `p4 login`
I've tried including P4PASSWD as a environment variable inside p4dtcl.conf

**Comment by saadbruno** [comment]
there should be a file called `output.log` in the same directory as the script, considering you kept like 15 uncommented.
Can you paste the contents of it so we can take a look? You can remove sensitive information like the server IP, that's not important.

Checking this file is good so we can take a look if the p4 trigger actually tried to run your script. You mentioned you weren't sure if the trigger worked, and that's how we can know.

--

A few things that come to mind given the info you posted:

 > I've tried using `p4 login`
 What happened when you ran it? Did it error? Did it log you in, but the webhook still didn't work?
 
 Another thing is that you mentioned:
 > When I run the script manually, my discord webhook works
 But also mentioned:
 > Perforce password (P4PASSWD) invalid or unset. I'm not too sure how to set this.
 It seems to me that you set up the p4 login on the wrong linux user.
 
 Remember that when configuring the Step 1 in the README, you have to execute it as the same user running your perforce server, and **not** your default linux user.
 
 Maybe your login was successful, but on the wrong user, so when perforce triggers after a changelist, the script itself can't read the contents of it cause it's not logged in.
  
 Be sure to:
 
1. Log in as the `perforce` user (or whatever the user running the perforce server is)
2. Set your Perforce login by running the p4 login command

**Comment by dtnguyen277** [comment]
Hey, I actually figured out the problem.

The trigger was functioning fine, the problem was that the linux user "perforce" did not have access to the script so what I had to do was p4 trust the fingerprint, and p4 login with my password through the .sh script. I tried setting P4PASSWD in the environment but that didn't seem to work.

Thanks for making this script its really awesome!
